# Global settings applied to the whole site.
[build]
  # Directory to change to before starting a build. 
  base = "/"

  # The command to run to build your site.
  command = "npm run build"

  publish = "dist/"

# Redirects
[[redirects]]
  from = "/old-path"
  to = "/new-path"
  status = 301
  force = true
