# MovieVerse API Requests

# Before running this, be sure that the Django backend server is up and running!

@base_url = http://127.0.0.1:8000

### Movies

# Get all movies
GET {{base_url}}/api/movies/

# Get a specific movie (replace 123 with the actual movie ID)
###
GET{{base_url}}/api/movies/123/

# Filter movies by title (replace "Inception" with your search term)
###
GET{{base_url}}/api/movies/?search=Inception


### Genres

# Get all genres
GET {{base_url}}/api/genres/


### People

# Get all people
GET {{base_url}}/api/people/

# Get a specific person (replace 456 with the actual person ID)
###
GET{{base_url}}/api/people/456/


### Reviews (Assuming you have authentication set up for these)

# Get all reviews
GET {{base_url}}/api/reviews/

# Get reviews for a specific movie (replace 123 with the movie ID)
###
GET{{base_url}}/api/reviews/?movie_id=123

# Get reviews by a specific user (replace 789 with the user ID)
###
GET{{base_url}}/api/reviews/?user_id=789

### Users

# Get all users
GET {{base_url}}/api/users/

# Get a specific user (replace 789 with the actual user ID)
###
GET{{base_url}}/api/users/789/
