openapi: 3.0.0
info:
  title: MovieVerse API
  version: 1.0.0
  description: API for MovieVerse, a platform for exploring and reviewing movies.
servers:
  - url: http://localhost:8000/api
    description: Development server

paths:
  /movies:
    get:
      summary: List all movies
      responses:
        '200':
          description: A list of movies
#          content:
#            application/json:
#              schema:
#                type: array
#                items:
#                  $ref: '#/components/schemas/Movie'

  /movies/{id}:
    get:
      summary: Get a movie by its ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Details of a movie
#          content:
#            application/json:
#              schema:
#                $ref: '#/components/schemas/Movie'
        '404':
          description: Movie not found

components:
  schemas:
    Movie:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        overview:
          type: string
        releaseDate:
          type: string
          format: date
        rating:
          type: number
          format: float
        genres:
          type: array
          items:
            type: string
