# Generated by Django 3.2 on 2024-06-19 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieverse', '0003_auto_20240619_0611'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='genre',
            table='Genre',
        ),
        migrations.AlterModelTable(
            name='movie',
            table='MovieMetadata',
        ),
        migrations.AlterModelTable(
            name='review',
            table='reviews',
        ),
    ]
