# Generated by Django 3.2 on 2024-06-19 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieverse', '0005_auto_20240619_0651'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='genre',
            table='genres',
        ),
    ]
